"""Remove UserOTP table

Revision ID: fb6b7b937158
Revises: 728b16d0588b
Create Date: 2026-06-16 23:41:41.906803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb6b7b937158'
down_revision = '728b16d0588b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_otps')
    with op.batch_alter_table('career_recommendations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('learning_roadmaps', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('resume_analysis', schema=None) as batch_op:
        batch_op.alter_column('sections_detected_json',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('skills_found_json',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('missing_keywords_json',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('suggestions_json',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('analyzed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('interests_json',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('certifications_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.alter_column('projects_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'::text"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('projects_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.alter_column('certifications_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.alter_column('interests_json',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('resume_analysis', schema=None) as batch_op:
        batch_op.alter_column('analyzed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('suggestions_json',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('missing_keywords_json',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('skills_found_json',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('sections_detected_json',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('learning_roadmaps', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('career_recommendations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    op.create_table('user_otps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('otp', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_otps_pkey'))
    )
    # ### end Alembic commands ###
